# Generated by Django 5.1.9 on 2025-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadImage', models.ImageField(upload_to='tree_images/')),
                ('Result', models.CharField(max_length=255)),
            ],
        ),
    ]
