# Generated by Django 5.1.9 on 2025-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treecare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='Disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='Species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
