# Generated by Django 5.2.6 on 2025-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treecare_app', '0002_tree_disease_tree_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='UploadImage',
            field=models.ImageField(max_length=255, upload_to='tree_images/'),
        ),
    ]
